[project]
name = "hospital-bot-demo"
version = "0.1.0"
description = "A hospital bot demo using Langchain"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
   "neo4j",
   "retry"
]

[project.optional-dependencies]
dev = ["black", "flake8"]
